Ben C IESG review fixes
core-wg/senml-spec pull request #106
Opened 2018-04-19 16:34 UTC by akeranen

2018-04-25 21:38 UTC, fluffy approved these changes
LGTM

2018-05-03 08:56 UTC, cabo requested changes

2018-05-03 08:56 UTC, cabo commented on draft-ietf-core-senml.md
> +format and new media types for carrying simple sensor information in a
What is new about the media types that is not new about the format?  s/new//.

2018-05-03 08:56 UTC, cabo commented on draft-ietf-core-senml.md
> +(*) Data Value is base64 encoded string with URL safe alphabet as
Maybe we can be bold and say:

Data Value is a sequence of bytes represented as a base64 encoded string...

2018-05-03 15:51 UTC, merged