Ekr IESG review fixes
core-wg/senml-spec pull request #108
Opened 2018-04-19 17:43 UTC by akeranen

2018-04-25 21:35 UTC, fluffy approved these changes
LGTM

2018-05-03 08:51 UTC, cabo requested changes

2018-05-03 08:51 UTC, cabo commented on draft-ietf-core-senml.md
> +before saving the SenML in a document database.
SenML information?  Not sure that "the SenML" is a great construction.

2018-05-03 08:51 UTC, cabo commented on draft-ietf-core-senml.md
>  another container or transport protocol such as S/MIME {{?RFC5751}} or
Maybe s/transport/transfer/.  (There are no transport protocols in the list.)

2018-05-03 15:52 UTC, cabo approved these changes

2018-05-03 15:54 UTC, merged