Moved and updated Security considerations
core-wg/senml-spec pull request #93
Opened 2017-11-12 16:46 UTC by akeranen

2017-11-12 18:01 UTC, cabo requested changes

2017-11-12 18:01 UTC, cabo commented on draft-ietf-core-senml.md
> +Security considerations: See {{sec-sec}}.
Since this is text that goes into the media type registry, this would need to be "See {{sec-sec}} of RFCthis".

2017-11-12 18:01 UTC, cabo commented on draft-ietf-core-senml.md
> +confidentiality protection, such as patient health information. SenML
The SenML...

2017-11-12 18:01 UTC, cabo commented on draft-ietf-core-senml.md
> +transport or transfer protocol that carries it to provide security.
s/transport or //
or
s/transport or transfer //

2017-11-13 04:37 UTC, fluffy requested changes
The IANA types review list explicitly wanted all of this repeated because they don't read the draft on the email and each type needs it's own email. It is insane. So I would not make this change.

2017-11-13 06:05 UTC, akeranen commented
Alternatively we can have the same text 9 times instead of 8

2017-11-26 16:54 UTC, cabo approved these changes
LGTM

2017-11-29 18:52 UTC, akeranen commented
Alexey confirmed in the CoRE session that this is OK, so let's go forward with this.

2017-11-29 18:52 UTC, merged